export const InputData = [
    { name: 'name', type: 'text', placeholder: 'Name' },
    { name: 'fatherName', type: 'text', placeholder: 'Father Name' },
    { name: 'dateOfJoining', type: 'text', placeholder: 'Date of Joining' },
    { name: 'Class', type: 'text', placeholder: 'Class' },
    { name: 'section', type: 'text', placeholder: 'Section' },
    {
      name: 'gender',
      type: 'select', 
      placeholder: 'Select Gender', 
      options: ['Male', 'Female', 'Other'], 
    },
    {
      name: 'last_qualification',
      type: 'select', 
      placeholder: 'Last Qualification', 
      options: ["Matric", "Inter", "BS / BSc / BBA", "MA / MSc / MPhil", "Ph.D."], 
    },
    {
      name: 'designation',
      type: 'select', 
      placeholder: 'Select Designation', 
      options: ['Principle', 'Admin', 'Teacher'], 
    },
    { name: 'salary', type: 'number', placeholder: 'Salary' }, 
    { name: 'dateOfBirth', type: 'text', placeholder: 'Date of Birth' }, 
    { name: 'CNIC_No', type: 'text', placeholder: 'CNIC_No' }, 
    { name: 'address', type: 'text', placeholder: 'Home Address' },
    { name: 'phone', type: 'text', placeholder: 'Phone Number', length: 11 },
    { name: 'email', type: 'email', placeholder: 'Email' },
    { name: 'password', type: 'password', placeholder: 'Password' },
  ];